# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the 'addonPackager' package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: 'addonPackager' '1.0.3'\n"
"Report-Msgid-Bugs-To: 'nvda-translations@groups.io'\n"
"POT-Creation-Date: 2022-10-18 12:17+0200\n"
"PO-Revision-Date: 2022-10-24 12:22+0200\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 3.1\n"
"X-Poedit-SourceCharset: UTF-8\n"

#. Add-on summary, usually the user visible name of the addon.
#. Translators: Summary for this add-on to be shown on installation and add-on information.
#: buildVars.py:23 addon\globalPlugins\addonPackager\__init__.py:67
#: addon\globalPlugins\addonPackager\main.py:29
msgid "Utilidades para los complementos de NVDA"
msgstr "Dienstprogramme für NVDA-Add-ons"

#. Add-on description
#. Translators: Long description to be shown for this add-on on add-on information from add-ons manager
#: buildVars.py:26
msgid ""
"Conjunto de utilidades para un manejo fácil de complementos para NVDA.\n"
"\n"
"* Empaquetador de complementos.\n"
"* Instalador múltiple de complementos.\n"
"* Desinstala complementos.\n"
"* Habilita / deshabilita complementos.\n"
"* Modificador de manifiestos, instalados y desde archivo no instalado.\n"
"* Hacer / restaurar copias de seguridad de la configuración de NVDA.\n"
"* Documentación de complementos.\n"
"\n"
"Todas las áreas de fácil manejo y para ahorrar tiempo respecto al gestor de "
"complementos nativo de NVDA."
msgstr ""
"Dienstprogramme für die einfache Verwaltung von NVDA-Add-ons.\n"
"\n"
"* Add-on-Paketierer.\n"
"* Installationsprogramm für mehrere Add-ons.\n"
"* Deinstallieren Sie Add-ons.\n"
"* Aktivieren/Deaktivieren von Add-ons.\n"
"* Manifest Modifier, installiert und aus nicht installierter Datei.\n"
"* Erstellen/Wiederherstellen von Sicherungskopien der NVDA-Konfiguration.\n"
"* Dokumentation zum Zusatzmodul.\n"
"\n"
"Alle Bereiche sind benutzerfreundlich und zeitsparend im Vergleich zum NVDA-"
"eigenen Add-on-Manager."

#: addon\globalPlugins\addonPackager\__init__.py:35
msgid "&Utilidades para los complementos de NVDA"
msgstr "&Hilfsmittel für NVDA-Add-ons"

#: addon\globalPlugins\addonPackager\__init__.py:52
msgid ""
"Hay una acción pendiente de reiniciar NVDA.\n"
"\n"
"Por motivos de seguridad el complemento no podrá ser usado hasta que no "
"reinicie.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"NVDA muss neu gestartet werden.\n"
"\n"
"Das Addon kann aus Sicherheitsgründen erst nach einem Neustart verwendet "
"werden.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\__init__.py:57
msgid "Pregunta"
msgstr "Dialogfeld"

#: addon\globalPlugins\addonPackager\__init__.py:67
msgid "Muestra la ventana de Utilidades para los complementos de NVDA"
msgstr "Zeigt das Fenster Dienstprogramme für NVDA-Add-ons an"

#: addon\globalPlugins\addonPackager\__init__.py:77
#: addon\globalPlugins\addonPackager\__init__.py:79
msgid ""
"Ya hay una instancia de Utilidades para los complementos de NVDA abierta."
msgstr "Es ist bereits eine Instanz von Utilities for NVDA add-ons geöffnet."

#: addon\globalPlugins\addonPackager\__init__.py:77
#: addon\globalPlugins\addonPackager\main.py:406
msgid "Información"
msgstr "Information"

#: addon\globalPlugins\addonPackager\main.py:47
msgid "Empaquetador de complementos"
msgstr "Komplementärpacker"

#: addon\globalPlugins\addonPackager\main.py:51
#: addon\globalPlugins\addonPackager\main.py:74
#: addon\globalPlugins\addonPackager\main.py:94
#: addon\globalPlugins\addonPackager\main.py:201
msgid "&Lista de complementos:"
msgstr "liste der Ergänzungen:"

#: addon\globalPlugins\addonPackager\main.py:60
#: addon\globalPlugins\addonPackager\main.py:83
#: addon\globalPlugins\addonPackager\main.py:103
#: addon\globalPlugins\addonPackager\main.py:129
#: addon\globalPlugins\addonPackager\main.py:170
msgid "&Selección"
msgstr "&Auswahl"

#: addon\globalPlugins\addonPackager\main.py:63
msgid "&Generar"
msgstr "&Erzeugen"

#: addon\globalPlugins\addonPackager\main.py:67
msgid "Instalador múltiple"
msgstr "Multi-Installer"

#: addon\globalPlugins\addonPackager\main.py:71
msgid "&Seleccione un directorio con complementos a instalar..."
msgstr "&Wählen Sie ein Verzeichnis mit zu installierenden Plug-ins..."

#: addon\globalPlugins\addonPackager\main.py:86
msgid "&Instalar"
msgstr "&Installieren"

#: addon\globalPlugins\addonPackager\main.py:90
msgid "Desinstala complementos"
msgstr "Add-ons deinstallieren"

#: addon\globalPlugins\addonPackager\main.py:106
msgid "&Desinstalar"
msgstr "&Deinstallieren"

#: addon\globalPlugins\addonPackager\main.py:110
msgid "Habilita / deshabilita complementos"
msgstr "Aktivieren/Deaktivieren von Erweiterungen"

#: addon\globalPlugins\addonPackager\main.py:114
msgid "&Lista de complementos habilitados:"
msgstr "liste der aktivierten Erweiterungen:"

#: addon\globalPlugins\addonPackager\main.py:120
msgid "&Lista de complementos deshabilitados:"
msgstr "liste der deaktivierten Erweiterungen:"

#: addon\globalPlugins\addonPackager\main.py:132
#: addon\globalPlugins\addonPackager\main.py:173
msgid "&Procesar"
msgstr "&Prozess"

#: addon\globalPlugins\addonPackager\main.py:136
msgid "Modificador de manifiestos"
msgstr "Manifest Editor"

#: addon\globalPlugins\addonPackager\main.py:140
msgid "&Lista de complementos instalados:"
msgstr "liste der installierten Erweiterungen:"

#: addon\globalPlugins\addonPackager\main.py:149
msgid "Seleccione versión Mayor:"
msgstr "Wählen Sie die Hauptversion:"

#: addon\globalPlugins\addonPackager\main.py:155
msgid "Seleccione versión Menor:"
msgstr "Wählen Sie Minor Version:"

#: addon\globalPlugins\addonPackager\main.py:161
msgid "Seleccione una revisión:"
msgstr "Wählen Sie eine Revision aus:"

#: addon\globalPlugins\addonPackager\main.py:177
msgid "Hacer / restaurar copias de seguridad"
msgstr "Erstellen/Wiederherstellen von Backups"

#: addon\globalPlugins\addonPackager\main.py:181
msgid "&Hacer copias de seguridad:"
msgstr "&Zurücksetzen:"

#: addon\globalPlugins\addonPackager\main.py:190
msgid "&Crear copia de seguridad"
msgstr "&Sicherung erstellen"

#: addon\globalPlugins\addonPackager\main.py:193
msgid "&Restaurar copia de seguridad"
msgstr "&Wiederherstellung der Sicherung"

#: addon\globalPlugins\addonPackager\main.py:197
msgid "Documentación de complementos"
msgstr "Dokumentation der Erweiterung"

#: addon\globalPlugins\addonPackager\main.py:207
msgid "&Abrir documentación del complemento"
msgstr "&Zusätzliche Dokumentation öffnen"

#: addon\globalPlugins\addonPackager\main.py:213
msgid "&Estado:"
msgstr "&Zustand:"

#: addon\globalPlugins\addonPackager\main.py:225
msgid "&Aceptar"
msgstr "&OK"

#: addon\globalPlugins\addonPackager\main.py:228
msgid "&Cancelar"
msgstr "&Abbrechen"

#: addon\globalPlugins\addonPackager\main.py:231
msgid "Cerrar"
msgstr "Schließen"

#: addon\globalPlugins\addonPackager\main.py:315
#: addon\globalPlugins\addonPackager\main.py:581
#: addon\globalPlugins\addonPackager\main.py:625
#: addon\globalPlugins\addonPackager\main.py:862
msgid "Directorio Diccionarios"
msgstr "Verzeichnis Wörterbücher"

#: addon\globalPlugins\addonPackager\main.py:319
#: addon\globalPlugins\addonPackager\main.py:585
#: addon\globalPlugins\addonPackager\main.py:629
#: addon\globalPlugins\addonPackager\main.py:864
msgid "Directorio Perfiles"
msgstr "Verzeichnis-Profile"

#: addon\globalPlugins\addonPackager\main.py:323
#: addon\globalPlugins\addonPackager\main.py:589
#: addon\globalPlugins\addonPackager\main.py:633
#: addon\globalPlugins\addonPackager\main.py:866
msgid "Directorio Scratchpad"
msgstr "Scratchpad-Verzeichnis"

#: addon\globalPlugins\addonPackager\main.py:327
#: addon\globalPlugins\addonPackager\main.py:593
#: addon\globalPlugins\addonPackager\main.py:637
#: addon\globalPlugins\addonPackager\main.py:868
msgid "Fichero configuración disparadores de perfiles"
msgstr "Konfigurationsdatei für Profilauslöser"

#: addon\globalPlugins\addonPackager\main.py:330
#: addon\globalPlugins\addonPackager\main.py:596
#: addon\globalPlugins\addonPackager\main.py:640
#: addon\globalPlugins\addonPackager\main.py:870
msgid "Fichero de configuración gestos de entrada"
msgstr "Gestenkonfigurationsdatei eingeben"

#: addon\globalPlugins\addonPackager\main.py:333
#: addon\globalPlugins\addonPackager\main.py:599
#: addon\globalPlugins\addonPackager\main.py:643
#: addon\globalPlugins\addonPackager\main.py:872
msgid "Fichero de configuración de NVDA"
msgstr "NVDA-Konfigurationsdatei"

#: addon\globalPlugins\addonPackager\main.py:376
#: addon\globalPlugins\addonPackager\main.py:421
#: addon\globalPlugins\addonPackager\main.py:440
#: addon\globalPlugins\addonPackager\main.py:460
#: addon\globalPlugins\addonPackager\main.py:464
#: addon\globalPlugins\addonPackager\main.py:468
#: addon\globalPlugins\addonPackager\main.py:490
msgid "&Seleccionar todo"
msgstr "&Alles auswählen"

#: addon\globalPlugins\addonPackager\main.py:377
#: addon\globalPlugins\addonPackager\main.py:422
#: addon\globalPlugins\addonPackager\main.py:441
#: addon\globalPlugins\addonPackager\main.py:461
#: addon\globalPlugins\addonPackager\main.py:465
#: addon\globalPlugins\addonPackager\main.py:469
#: addon\globalPlugins\addonPackager\main.py:491
msgid "&Deseleccionar todo"
msgstr "Alle abwählen"

#: addon\globalPlugins\addonPackager\main.py:383
msgid "Tiene que seleccionar un complemento para continuar."
msgstr "Sie müssen eine Erweiterung auswählen, um fortzufahren."

#: addon\globalPlugins\addonPackager\main.py:383
#: addon\globalPlugins\addonPackager\main.py:428
#: addon\globalPlugins\addonPackager\main.py:447
#: addon\globalPlugins\addonPackager\main.py:478
#: addon\globalPlugins\addonPackager\main.py:506
#: addon\globalPlugins\addonPackager\main.py:747
#: addon\globalPlugins\addonPackager\main.py:879
msgid "Error"
msgstr "Fehler"

#. Botón selecciona directorio con complementos instalador.
#: addon\globalPlugins\addonPackager\main.py:386
#: addon\globalPlugins\addonPackager\main.py:400
msgid "Seleccione un directorio:"
msgstr "Wählen Sie ein Verzeichnis:"

#: addon\globalPlugins\addonPackager\main.py:406
msgid "No se encontraron complementos en el directorio que selecciono."
msgstr ""
"In dem von ihnen gewählten Verzeichnis wurden keine Erweiterungen gefunden."

#: addon\globalPlugins\addonPackager\main.py:428
#: addon\globalPlugins\addonPackager\main.py:447
#: addon\globalPlugins\addonPackager\main.py:478
#: addon\globalPlugins\addonPackager\main.py:747
msgid "Necesita elegir al menos un complemento para continuar."
msgstr "Sie müssen mindestens eine Erweiterung auswählen, um fortzufahren."

#: addon\globalPlugins\addonPackager\main.py:466
msgid "Complementos &habilitados"
msgstr "Erweiterungen & aktiviert"

#: addon\globalPlugins\addonPackager\main.py:470
msgid "Complementos &deshabilitados"
msgstr "Erweiterungen & Deaktiviert"

#: addon\globalPlugins\addonPackager\main.py:496
msgid "Procesar &instalados"
msgstr "Prozess &Installation"

#: addon\globalPlugins\addonPackager\main.py:497
msgid "Procesar un archivo de &complemento"
msgstr "Bearbeitung einer Erweiterungsdatei"

#: addon\globalPlugins\addonPackager\main.py:506
#: addon\globalPlugins\addonPackager\main.py:879
msgid ""
"Necesita elegir al menos un elemento de copia de seguridad de la lista para "
"continuar."
msgstr ""
"Sie müssen mindestens einen Sicherungsartikel aus der Liste auswählen, um "
"fortzufahren."

#. Botón restaurar copia de seguridad
#: addon\globalPlugins\addonPackager\main.py:512
#: addon\globalPlugins\addonPackager\main.py:528
msgid "Archivo de copia de seguridad de NVDA (*.nvda-backup)|*.nvda-backup"
msgstr "NVDA-Sicherungsdatei (*.nvda-backup)|*.nvda-backup"

#: addon\globalPlugins\addonPackager\main.py:513
msgid "Guardar la copia de seguridad en..."
msgstr "Speichern Sie die Sicherungskopie in..."

#: addon\globalPlugins\addonPackager\main.py:529
msgid "Seleccione un archivo de copia de seguridad de NVDA"
msgstr "Wählen Sie eine NVDA-Sicherungsdatei"

#. Manifiestos procesar fichero.
#: addon\globalPlugins\addonPackager\main.py:761
msgid "Complemento de NVDA (*.nvda-addon)|*.nvda-addon"
msgstr "NVDA-Erweiterung (*.nvda-Addon)|*.nvda-Addon"

#: addon\globalPlugins\addonPackager\main.py:762
msgid "Seleccione un complemento de NVDA"
msgstr "Wählen Sie eine NVDA Erweiterung"

#: addon\globalPlugins\addonPackager\main.py:823
msgid "Restaurar copia de seguridad de NVDA"
msgstr "NVDA-Sicherung wiederherstellen"

#: addon\globalPlugins\addonPackager\main.py:829
msgid "&Contenido de la copia de seguridad:"
msgstr "&Inhalt des Backups:"

#: addon\globalPlugins\addonPackager\main.py:838
msgid "&Restaurar"
msgstr "&Wiederherstellen"

#: addon\globalPlugins\addonPackager\main.py:841
msgid "&Cerrar"
msgstr "&Schließen"

#: addon\globalPlugins\addonPackager\utilidades.py:162
msgid "Creando el complemento: {} {}"
msgstr "Erstellen des Komplements: {} {}"

#: addon\globalPlugins\addonPackager\utilidades.py:166
msgid ""
"Se generaron correctamente todos los complementos.\n"
"\n"
"Pulse aceptar para continuar."
msgstr ""
"Alle Erweiterungspakete wurden korrekt erstellt.\n"
"\n"
"Klicken Sie auf OK, um fortzufahren."

#: addon\globalPlugins\addonPackager\utilidades.py:172
#: addon\globalPlugins\addonPackager\utilidades.py:254
#: addon\globalPlugins\addonPackager\utilidades.py:304
#: addon\globalPlugins\addonPackager\utilidades.py:436
#: addon\globalPlugins\addonPackager\utilidades.py:490
#: addon\globalPlugins\addonPackager\utilidades.py:553
msgid ""
"Se produjo un error inesperado. \n"
"\n"
"Error: {}\n"
"\n"
"Vuelva a intentarlo."
msgstr ""
"Es ist ein unerwarteter Fehler aufgetreten\n"
"\n"
"Fehler: {}\n"
"\n"
"Bitte versuchen Sie es erneut."

#: addon\globalPlugins\addonPackager\utilidades.py:195
msgid "Instalando el complemento: {}"
msgstr "Installation der Erweiterung: {}"

#: addon\globalPlugins\addonPackager\utilidades.py:218
msgid ""
"Se completo la instalación correctamente.\n"
"\n"
"NVDA necesita reiniciarse para aplicar las instalaciones.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Die Installation wurde erfolgreich abgeschlossen.\n"
"\n"
"NVDA muss neu gestartet werden, um die  Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:228
msgid ""
"No se pudo instalar el complemento.\n"
"\n"
"Fallo de compatibilidad.\n"
"\n"
"Busque un complemento compatible."
msgstr ""
"Das Add-on konnte nicht installiert werden.\n"
"\n"
"Leider sind Kompatibilitätsprobleme aufgetreten.\n"
"\n"
"Suchen Sie nach einem kompatiblen Add-on."

#: addon\globalPlugins\addonPackager\utilidades.py:239
msgid ""
"Se completo la instalación correctamente.\n"
"\n"
"Pero hay complementos que no se pudieron instalar.\n"
"\n"
"Los siguientes complementos son incompatibles, busque una versión "
"compatible:\n"
"\n"
"{}\n"
"\n"
"NVDA necesita reiniciarse para aplicar las instalaciones.\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Installation erfolgreich abgeschlossen.\n"
"\n"
"Es gibt jedoch Erweiterungen, die nicht installiert werden konnten.\n"
"\n"
"Die folgenden Erweiterungen sind nicht kompatibel, bitte suchen Sie nach "
"einer kompatiblen Version:\n"
"\n"
"{}\n"
"\n"
"NVDA muss neu gestartet werden, um die Installationen abzuschließen.\n"
"Möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:263
msgid ""
"Se produjo un error inesperado. \n"
"\n"
"Error: {}\n"
"\n"
"No obstante hubo complementos que se instalaron y NVDA necesita reiniciar "
"para aplicar los cambios.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Es ist ein unerwarteter Fehler aufgetreten\n"
"\n"
"Fehler: {}\n"
"\n"
"Es wurden jedoch Add-ons installiert und NVDA muss neu gestartet werden, um "
"die Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:288
msgid "Desinstalando el complemento: {}"
msgstr "Deinstallation der Erweiterungen: {}"

#: addon\globalPlugins\addonPackager\utilidades.py:295
msgid ""
"Se completo la desinstalación correctamente.\n"
"\n"
"NVDA necesita reiniciarse para aplicar los cambios.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Die Deinstallation wurde erfolgreich abgeschlossen.\n"
"\n"
"NVDA muss neu gestartet werden, um die Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:313
msgid ""
"Se produjo un error inesperado. \n"
"\n"
"Error: {}\n"
"\n"
"No obstante hubo complementos que se desinstalaron y NVDA necesita reiniciar "
"para aplicar los cambios.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Es ist ein unerwarteter Fehler aufgetreten\n"
"\n"
"Fehler: {}\n"
"\n"
"Allerdings wurden einige Add-ons deinstalliert und NVDA muss neu gestartet "
"werden, um die Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:361
msgid "Buscando complementos en {}..."
msgstr "Suche nach Ergänzungen zu {}..."

#: addon\globalPlugins\addonPackager\utilidades.py:365
msgid "No hay complementos compatibles en el directorio."
msgstr "Es gibt keine kompatiblen Add-ons im Verzeichnis."

#: addon\globalPlugins\addonPackager\utilidades.py:369
msgid ""
"Se completo con éxito la extracción de información de los complementos.\n"
"\n"
"No obstante, el directorio que introdujo contiene complementos no "
"compatibles.\n"
"\n"
"* Complementos con fallo en el manifiesto: {}.\n"
"\n"
"{}\n"
"\n"
"* Complementos no compatibles con la api actual: {}.\n"
"\n"
"{}\n"
"\n"
"Pulse aceptar para continuar."
msgstr ""
"Die Extraktion von Informationen aus den Add-ons wurde erfolgreich "
"abgeschlossen.\n"
"\n"
"Das von Ihnen angegebene Verzeichnis enthält jedoch nicht unterstützte "
"Erweiterungen.\n"
"\n"
"* Erweiterungen mit Manifestfehler: {}.\n"
"\n"
"{}\n"
"\n"
"* Erweiterungen nicht kompatibel mit aktueller API: {}.\n"
"\n"
"{}\n"
"\n"
"Klicken Sie auf Akzeptieren, um fortzufahren."

#: addon\globalPlugins\addonPackager\utilidades.py:385
msgid ""
"Se completo con éxito la extracción de información de los complementos.\n"
"\n"
"Pulse aceptar para continuar."
msgstr ""
"Die Extraktion von Informationen aus den Erweiterungen wurde erfolgreich "
"abgeschlossen.\n"
"\n"
"Klicken Sie auf OK, um fortzufahren."

#: addon\globalPlugins\addonPackager\utilidades.py:408
msgid "Deshabilitando complementos..."
msgstr "Deaktivieren von Erweiterungen..."

#: addon\globalPlugins\addonPackager\utilidades.py:418
msgid "Habilitando complementos..."
msgstr "Aktivieren von Erweiterungen..."

#: addon\globalPlugins\addonPackager\utilidades.py:427
msgid ""
"Se completo el proceso de habilitar y deshabilitar correctamente.\n"
"\n"
"NVDA necesita reiniciarse para aplicar los cambios.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Der Prozess der Aktivierung und Deaktivierung wurde erfolgreich "
"abgeschlossen.\n"
"\n"
"NVDA muss neu gestartet werden, um die Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:445
msgid ""
"Se produjo un error inesperado. \n"
"\n"
"Error: {}\n"
"\n"
"No obstante hubo complementos que se habilitaron o deshabilitaron y NVDA "
"necesita reiniciar para aplicar los cambios.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Es ist ein unerwarteter Fehler aufgetreten\n"
"\n"
"Fehler: {}\n"
"\n"
"Trotzdem wurden einige Erweiterungen aktiviert oder deaktiviert und NVDA "
"muss neu gestartet werden, um die Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:474
msgid "Cambiando el manifiesto al complemento: {}"
msgstr "Ändern des Manifests in das Komplement: {}"

#: addon\globalPlugins\addonPackager\utilidades.py:481
msgid ""
"Se cambiaron los manifiestos correctamente.\n"
"\n"
"Para que la acción tenga efecto NVDA tiene que reiniciarse.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Die Manifest-Dateien wurden korrekt geändert.\n"
"\n"
"Damit die Änderungen wirksam werden, muss NVDA neu gestartet werden.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:499
msgid ""
"Se produjo un error inesperado. \n"
"\n"
"Error: {}\n"
"\n"
"No obstante hubo complementos que se les cambio el manifiesto y NVDA "
"necesita reiniciar para aplicar los cambios.\n"
"\n"
"¿Desea reiniciar NVDA ahora?"
msgstr ""
"Es ist ein unerwarteter Fehler aufgetreten\n"
"\n"
"Fehler: {}\n"
"\n"
"Jedoch wurden einige Manifest-Dateien geändert, und NVDA muss neu gestartet "
"werden, um die Änderungen zu übernehmen.\n"
"\n"
"möchten Sie NVDA jetzt neu starten?"

#: addon\globalPlugins\addonPackager\utilidades.py:528
msgid "Trabajando en el complemento: {}"
msgstr "Arbeiten im Komplement: {}"

#: addon\globalPlugins\addonPackager\utilidades.py:543
msgid ""
"Se cambio correctamente el manifiesto.\n"
"\n"
"Se genero un complemento con el manifiesto cambiado en:\n"
"\n"
"{}\n"
"\n"
"Pulse aceptar para continuar."
msgstr ""
"Die Manifest-Datei wurde korrekt geändert.\n"
"\n"
"Es wurde eine Erweiterung mit der geänderten Manifest-Datei erstellt:\n"
"\n"
"{}\n"
"\n"
"Klicken Sie auf OK, um fortzufahren."

#. Diccionario
#: addon\globalPlugins\addonPackager\utilidades.py:581
msgid "Añadiendo el directorio de diccionarios..."
msgstr "Hinzufügen des Wörterbuchverzeichnisses..."

#: addon\globalPlugins\addonPackager\utilidades.py:587
msgid ""
"No se pudo agregar el directorio de diccionarios a la copia de seguridad."
msgstr ""
"Das Wörterbuchverzeichnis konnte der Sicherung nicht hinzugefügt werden."

#. Perfiles
#: addon\globalPlugins\addonPackager\utilidades.py:589
msgid "Añadiendo el directorio de Perfiles..."
msgstr "Hinzufügen des Verzeichnisses Profiles..."

#: addon\globalPlugins\addonPackager\utilidades.py:595
msgid "No se pudo agregar el directorio de Perfiles a la copia de seguridad."
msgstr ""
"Das Verzeichnis Profiles konnte der Sicherung nicht hinzugefügt werden."

#. Scratchpad
#: addon\globalPlugins\addonPackager\utilidades.py:597
msgid "Añadiendo el directorio de Scratchpad..."
msgstr "Hinzufügen des Scratchpad-Verzeichnisses..."

#: addon\globalPlugins\addonPackager\utilidades.py:603
msgid "No se pudo agregar el directorio de Scratchpad a la copia de seguridad."
msgstr "Das Scratchpad-Verzeichnis konnte dem Backup nicht hinzugefügt werden."

#. Fichero configuración disparadores de perfiles
#: addon\globalPlugins\addonPackager\utilidades.py:606
msgid "Añadiendo el Fichero configuración disparadores de perfiles..."
msgstr "Hinzufügen der Profilauslöser-Konfigurationsdatei..."

#: addon\globalPlugins\addonPackager\utilidades.py:613
#: addon\globalPlugins\addonPackager\utilidades.py:615
msgid ""
"No se pudo agregar el Fichero configuración disparadores de perfiles a la "
"copia de seguridad."
msgstr ""
"Die Profilauslöser-Konfigurationsdatei konnte dem Backup nicht hinzugefügt "
"werden."

#. Fichero de configuración gestos de entrada
#: addon\globalPlugins\addonPackager\utilidades.py:618
msgid "Añadiendo el Fichero de configuración gestos de entrada..."
msgstr "Hinzufügen der Konfigurationsdatei für Eingabegesten..."

#: addon\globalPlugins\addonPackager\utilidades.py:625
#: addon\globalPlugins\addonPackager\utilidades.py:627
msgid ""
"No se pudo agregar el Fichero de configuración gestos de entrada a la copia "
"de seguridad."
msgstr ""
"Die Konfigurationsdatei für die Eingabegesten konnte nicht zum Backup "
"hinzugefügt werden."

#. Fichero de configuración de NVDA
#: addon\globalPlugins\addonPackager\utilidades.py:630
msgid "Añadiendo el Fichero de configuración de NVDA..."
msgstr "Hinzufügen der NVDA-Konfigurationsdatei..."

#: addon\globalPlugins\addonPackager\utilidades.py:637
#: addon\globalPlugins\addonPackager\utilidades.py:639
msgid ""
"No se pudo agregar el Fichero de configuración de NVDA a la copia de "
"seguridad."
msgstr ""
"Die NVDA-Konfigurationsdatei konnte nicht zum Backup hinzugefügt werden."

#: addon\globalPlugins\addonPackager\utilidades.py:652
msgid ""
"Se creo la copia de seguridad correctamente en:\n"
"\n"
"{}\n"
"\n"
"Pulse aceptar para continuar."
msgstr ""
"Die Sicherung wurde erfolgreich in erstellt:\n"
"\n"
"{}\n"
"\n"
"Drücken Sie auf Akzeptieren, um fortzufahren."

#: addon\globalPlugins\addonPackager\utilidades.py:665
msgid ""
"Se produjo el siguiente error:\n"
"\n"
"{}\n"
"\n"
"No se pudo crear la copia de seguridad."
msgstr ""
"Der folgende Fehler ist aufgetreten:\n"
"\n"
"{}\n"
"\n"
"Die Sicherung konnte nicht erstellt werden."

#: addon\globalPlugins\addonPackager\utilidades.py:673
msgid ""
"Se produjeron los siguientes errores:\n"
"\n"
"{}\n"
"\n"
"No se pudo crear la copia de seguridad."
msgstr ""
"Die folgenden Fehler sind aufgetreten:\n"
"\n"
"{}\n"
"\n"
"Die Sicherung konnte nicht erstellt werden."

#. Diccionario
#: addon\globalPlugins\addonPackager\utilidades.py:699
msgid "Restaurando el directorio de diccionarios..."
msgstr "Wiederherstellung des Wörterbuchverzeichnisses..."

#: addon\globalPlugins\addonPackager\utilidades.py:708
#: addon\globalPlugins\addonPackager\utilidades.py:710
msgid "No se pudo restaurar el directorio de diccionarios."
msgstr "Das Wörterbuchverzeichnis konnte nicht wiederhergestellt werden."

#. Perfiles
#: addon\globalPlugins\addonPackager\utilidades.py:712
msgid "Restaurando el directorio de Perfiles..."
msgstr "Wiederherstellung des Profiles-Verzeichnisses..."

#: addon\globalPlugins\addonPackager\utilidades.py:721
#: addon\globalPlugins\addonPackager\utilidades.py:723
msgid "No se pudo restaurar el directorio de Perfiles."
msgstr "Das Verzeichnis Profiles konnte nicht wiederhergestellt werden."

#. Scratchpad
#: addon\globalPlugins\addonPackager\utilidades.py:726
msgid "Restaurando el directorio de Scratchpad..."
msgstr "Wiederherstellung des Scratchpad-Verzeichnisses..."

#: addon\globalPlugins\addonPackager\utilidades.py:735
#: addon\globalPlugins\addonPackager\utilidades.py:737
msgid "No se pudo restaurar el directorio de Scratchpad."
msgstr "Das Scratchpad-Verzeichnis konnte nicht wiederhergestellt werden."

#. Fichero configuración disparadores de perfiles
#: addon\globalPlugins\addonPackager\utilidades.py:740
msgid "Restaurando el Fichero configuración disparadores de perfiles..."
msgstr "Wiederherstellung der Konfigurationsdatei für Profilauslöser..."

#: addon\globalPlugins\addonPackager\utilidades.py:754
#: addon\globalPlugins\addonPackager\utilidades.py:756
#: addon\globalPlugins\addonPackager\utilidades.py:758
msgid "No se pudo restaurar el Fichero configuración disparadores de perfiles."
msgstr ""
"Die Konfigurationsdatei der Profilauslöser konnte nicht wiederhergestellt "
"werden."

#. Fichero configuración gestos de entrada
#: addon\globalPlugins\addonPackager\utilidades.py:761
msgid "Restaurando el Fichero configuración gestos de entrada..."
msgstr "Wiederherstellen der Konfigurationsdatei für Eingabegesten..."

#: addon\globalPlugins\addonPackager\utilidades.py:775
#: addon\globalPlugins\addonPackager\utilidades.py:777
msgid "No se pudo restaurar el Fichero configuración de gestos de entrada."
msgstr ""
"Die Konfigurationsdatei für Eingabegesten konnte nicht wiederhergestellt "
"werden."

#: addon\globalPlugins\addonPackager\utilidades.py:779
msgid "No se pudo restaurar el Fichero configuración gestos de entrada."
msgstr ""
"Die Konfigurationsdatei für Eingabegesten konnte nicht wiederhergestellt "
"werden."

#. Fichero configuración de NVDA
#: addon\globalPlugins\addonPackager\utilidades.py:782
msgid "Restaurando el Fichero configuración de NVDA..."
msgstr "Wiederherstellung der NVDA-Konfigurationsdatei..."

#: addon\globalPlugins\addonPackager\utilidades.py:796
#: addon\globalPlugins\addonPackager\utilidades.py:798
#: addon\globalPlugins\addonPackager\utilidades.py:800
msgid "No se pudo restaurar el Fichero configuración de NVDA."
msgstr "Die NVDA-Konfigurationsdatei konnte nicht wiederhergestellt werden."

#: addon\globalPlugins\addonPackager\utilidades.py:808
msgid ""
"La restauración fue un éxito.\n"
"\n"
"Al restaurar la configuración de NVDA es necesario reiniciar el lector.\n"
"\n"
"Pulse aceptar o cerrar para reiniciar."
msgstr ""
"Die Restaurierung war ein Erfolg.\n"
"\n"
"Die Wiederherstellung der NVDA-Konfiguration erfordert einen Neustart des "
"Lesegeräts.\n"
"\n"
"Drücken Sie Akzeptieren oder Schließen, um neu zu starten."

#: addon\globalPlugins\addonPackager\utilidades.py:818
msgid ""
"Se produjo el siguiente error:\n"
"\n"
"{}\n"
"\n"
"No se pudo restaurar toda la copia de seguridad.\n"
"\n"
"Pero hay elementos que si pudieron ser restaurados.\n"
"\n"
"Al restaurar la configuración de NVDA es necesario reiniciar el lector.\n"
"\n"
"Pulse cancelar o cerrar para reiniciar."
msgstr ""
"Der folgende Fehler ist aufgetreten:\n"
"\n"
"{}\n"
"\n"
"Die gesamte Sicherung konnte nicht wiederhergestellt werden.\n"
"\n"
"Aber es gibt Dinge, die wiederhergestellt werden könnten.\n"
"\n"
"Die Wiederherstellung der NVDA-Konfiguration erfordert einen Neustart des "
"Lesegeräts.\n"
"\n"
"Drücken Sie Abbrechen oder Schließen, um neu zu starten."

#: addon\globalPlugins\addonPackager\utilidades.py:832
msgid ""
"Se produjo el siguiente error:\n"
"\n"
"{}\n"
"\n"
"No se pudo restaurar la copia de seguridad.\n"
"\n"
"Pulse cancelar o cerrar para continuar."
msgstr ""
"Der folgende Fehler ist aufgetreten:\n"
"\n"
"{}\n"
"\n"
"Die Sicherung konnte nicht wiederhergestellt werden.\n"
"\n"
"Drücken Sie Abbrechen oder Schließen, um fortzufahren."

#: addon\globalPlugins\addonPackager\utilidades.py:843
msgid ""
"Se produjeron los siguientes errores:\n"
"\n"
"{}\n"
"\n"
"No se pudo restaurar toda la copia de seguridad.\n"
"\n"
"Pero hay elementos que si pudieron ser restaurados.\n"
"\n"
"Al restaurar la configuración de NVDA es necesario reiniciar el lector.\n"
"\n"
"Pulse cancelar o cerrar para reiniciar."
msgstr ""
"Die folgenden Fehler sind aufgetreten:\n"
"\n"
"{}\n"
"\n"
"Die gesamte Sicherung konnte nicht wiederhergestellt werden.\n"
"\n"
"Aber es gibt Dinge, die wiederhergestellt werden könnten.\n"
"\n"
"Die Wiederherstellung der NVDA-Konfiguration erfordert einen Neustart des "
"Lesegeräts.\n"
"\n"
"Drücken Sie Abbrechen oder Schließen, um neu zu starten."

#: addon\globalPlugins\addonPackager\utilidades.py:857
msgid ""
"Se produjeron los siguientes errores:\n"
"\n"
"{}\n"
"\n"
"No se pudo restaurar la copia de seguridad.\n"
"\n"
"Pulse cancelar o cerrar para continuar."
msgstr ""
"Die folgenden Fehler sind aufgetreten:\n"
"\n"
"{}\n"
"\n"
"Die Sicherung konnte nicht wiederhergestellt werden.\n"
"\n"
"Drücken Sie Abbrechen oder Schließen, um fortzufahren."
